name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Build
      run: nix-shell --run "cargo check --verbose --features=ssr"
    
    - name: Run tests
      run: nix-shell --run "cargo test --verbose --features=ssr"
