name: Build package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2

    - name: Install wasm32 target
      run: rustup target add wasm32-unknown-unknown

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
      
    - uses: cargo-bins/cargo-binstall@v1.14.4

    - name: Install Cargo Leptos
      run: cargo binstall cargo-leptos@0.2.42 --locked --no-confirm
      
    - name: Build application
      run: nix-shell --run "./build.sh"
      
    - name: Get version from tag
      id: get_version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}
        else
          VERSION="dev"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Using version: $VERSION"
      
    - name: Rename artifact with version
      run: |
        mv flashcard-app.tar.gz flashcard-app-v${{ steps.get_version.outputs.version }}-osx.tar.gz
      
    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: flashcard-app-v${{ steps.get_version.outputs.version }}-osx.tar.gz
